apiVersion: v1
kind: Service
metadata:
  name: validator${VALIDATOR_COUNT}
  labels:
    version: ${VERSION}
spec:
  selector:
    app: validator${VALIDATOR_COUNT}
    version: ${VERSION}
  ports:
  - port: 9876
    targetPort: 9876
    name: p2p
    protocol: TCP
