version: '3.5'

services:
  bios:
    build:
      target: local-stage
      context: ../
      dockerfile: ./Dockerfile
    container_name: bios
    environment:
      - EOS_PUB_KEY
      - EOS_PRIV_KEY
    volumes:
      - ../services/bios:/opt/application
    image: ${IMAGE_NAME}:${VERSION}
    depends_on:
      - "vault"
      - "wallet"
    ports:
      - 8888:8888

  wallet:
    build:
      target: local-stage
      context: ../
      dockerfile: ./Dockerfile
    container_name: wallet
    volumes:
      - ../services/wallet:/opt/application
    image: ${IMAGE_NAME}:${VERSION}
    depends_on:
      - "vault"
  vault:
    image: vault:1.4.3
    ports:
      - "8200:8200"
    container_name: vault
    volumes:
      - /tmp/vault/file:/vault/file:rw
      - ../services/vault/config:/vault/config:rw
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
    environment:
      VAULT_API_ADDR: http://0.0.0.0:8200/
      # VAULT_LOCAL_CONFIG: ${VAULT_LOCAL_CONFIG}
      # VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      # VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
