apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nodeos
  labels:
    version: ${VERSION}
parameters:
  fromBackup: ""
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
