apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api-node
  labels:
    version: ${VERSION}
spec:
  serviceName: api-node
  replicas: 1
  selector:
    matchLabels:
      app: api-node
      version: ${VERSION}
  template:
    metadata:
      labels:
        app: api-node
        version: ${VERSION}
    spec:
      initContainers:
        - name: init-seed
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -zvw3 seed 9876; do echo waiting for seed:9876; sleep 5; done;']
      containers:
        - name: nodeos
          image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${VERSION}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: nodeos-secrets
          env:
            - name: DATA_DIR
              value: /data/nodeos
            - name: CONFIG_DIR
              value: /data/nodeos/config
          ports:
            - name: p2p
              protocol: TCP
              containerPort: 9876
            - name: http
              protocol: TCP
              containerPort: 80
          livenessProbe:
            tcpSocket:
              port: p2p
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          volumeMounts:
            - name: data-directory
              mountPath: /data/nodeos
            - name: genesis
              mountPath: /opt/genesis
            - name: scripts
              mountPath: /opt/scripts
      volumes:
        - name: scripts
          configMap:
            name: api-node-config
            defaultMode: 0755
        - name: genesis
          configMap:
            name: genesis-config
  volumeClaimTemplates:
    - metadata:
        name: data-directory
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Gi
